"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Purpose = exports.AboutPET = void 0;
exports.AboutPET = {
    desktop: "O Programa de Educa\u00E7\u00E3o Tutorial (PET) \u00E9 um programa do governo federal \n    brasileiro de est\u00EDmulo a atividades de pesquisa, ensino e extens\u00E3o em n\u00EDvel de \n     gradua\u00E7\u00E3o. O PET foi criado e implantado em 1979 pela Coordena\u00E7\u00E3o de Aperfei\u00E7oamento \n    de Pessoal de N\u00EDvel Superior - CAPES, com o nome original de Programa Especial de\n    Treinamento, cujo objetivo era criar um grupo de elite intelectual, dedicado \u00E0 pesq uisa \n    e ao estudo. Em 2004, o nome foi alterado para Programa de Educa\u00E7\u00E3o Tutorial e adotou uma \n    nova filosofia. Os objetivos do programa, de acordo com o SESu, s\u00E3o a melhoria do ensino de \n    gradua\u00E7\u00E3o, a forma\u00E7\u00E3o acad\u00EAmica do aluno, a interdisciplinaridade, e o planejamento e \n    execu\u00E7\u00E3o de atividades acad\u00EAmicas diversificadas em grupos de tutoria. De 2006 a 2012  \n    ocorreu uma grande expans\u00E3o dos grupos PET no pa\u00EDs. Atualmente, existem 842 grupos distribu\u00EDdos \n    em 121 Institui\u00E7\u00F5es de Ensino Superior.'",
    mobile: "O Programa de Educa\u00E7\u00E3o Tutorial (PET) \u00E9 um programa do governo federal\n    brasileiro de est\u00EDmulo a atividades de pesquisa, ensino e extens\u00E3o em n\u00EDvel de\n    gradua\u00E7\u00E3o.  Os objetivos do programa, de acordo com o SESu, s\u00E3o a melhoria do ensino de\n    gradua\u00E7\u00E3o, a forma\u00E7\u00E3o acad\u00EAmica do aluno, a interdisciplinaridade, e o planejamento e\n    execu\u00E7\u00E3o de atividades acad\u00EAmicas diversificadas em grupos de tutoria. De 2006 a 2012\n    ocorreu uma grande expans\u00E3o dos grupos PET no pa\u00EDs. Atualmente, existem 842 grupos distribu\u00EDdos\n    em 121 Institui\u00E7\u00F5es de Ensino Superior."
};
exports.Purpose = {
    desktop: "O grupo PET do curso de An\u00E1lise e Desenvolvimento de Sistemas do IFSP S\u00E3o Carlos (PET/ADS/SCL) \n    foi criado em 2010. Desde sua cria\u00E7\u00E3o, o PET/ADS/SCL j\u00E1 desenvolveu diversas atividades voltadas \n    ao ensino, \u00E0 pesquisa e \u00E0 extens\u00E3o. O grupo \u00E9 formado por um docente tutor, at\u00E9 doze bolsistas e at\u00E9 seis \n    volunt\u00E1rios. Cada estudante do PET possui uma dedica\u00E7\u00E3o semanal de 20h e atua simultaneamente em diferentes\n    atividades, que v\u00E3o desde o estudo de t\u00E9cnicas de Computa\u00E7\u00E3o, linguagens e frameworks, at\u00E9 o desenvolvimento\n    de sistemas e a organiza\u00E7\u00E3o de eventos acad\u00EAmicos. Os estudantes tamb\u00E9m se envolvem em projetos de extens\u00E3o e\n    de pesquisa tanto locais quanto em parceria com outras institui\u00E7\u00F5es de ensino. Entre 2010 e 2022, o PET/ADS/SCL\n    teve como tutor o prof. Jo\u00E3o Luiz Franco. Atualmente, o grupo \u00E9 coordenado pelo prof. Lucas Oliveira.",
    mobile: "O grupo PET do curso de ADS do IFSP S\u00E3o Carlos (PET/ADS/SCL) foi criado em 2010. O grupo \u00E9 formado por um docente\n    tutor, at\u00E9 doze bolsistas e at\u00E9 seis volunt\u00E1rios. Cada estudante do PET possui uma dedica\u00E7\u00E3o semanal de 20h e atua\n    simultaneamente em diferentes atividades, que v\u00E3o desde o estudo de t\u00E9cnicas de Computa\u00E7\u00E3o, linguagens e frameworks,\n    at\u00E9 o desenvolvimento de sistemas e a organiza\u00E7\u00E3o de eventos acad\u00EAmicos. Os estudantes tamb\u00E9m se envolvem em\n    projetos de extens\u00E3o e de pesquisa tanto locais quanto em parceria com outras institui\u00E7\u00F5es de ensino. Atualmente,\n    o grupo \u00E9 coordenado pelo prof. Lucas Oliveira"
};
